/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER16
 */
public class Admin_dashboard extends javax.swing.JFrame {
    private String userEmail;

    /**
     * Creates new form home
     */
    public Admin_dashboard() {
        initComponents();
    
       
     
        
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // Add this variable at the top of the class
private String adminEmail;

// Update the constructor to accept the email
public Admin_dashboard(String email) {
    this.adminEmail = email; // Store the email
    initComponents();
    displayAdminName(); // Tawgon nato kini para mo-set sa text sa label
}


    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblAdminName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnUpdate = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnApprove = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Admin Dashboard");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 280, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 50));

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("USERS");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 220, 170, 30));

        jLabel7.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("LOGOUT");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 370, 170, 40));

        jLabel9.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("REPORTS");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 270, 170, 30));

        jLabel5.setBackground(new java.awt.Color(153, 153, 255));
        jLabel5.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("HOME");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 170, 170, 40));

        jLabel1.setBackground(new java.awt.Color(153, 153, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ACCOUNT");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 310, 170, 30));

        lblAdminName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAdminName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(lblAdminName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 170, 20));

        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 130, 110));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 150, 470));

        btnDelete.setBackground(new java.awt.Color(153, 153, 255));
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 60, 100, 30));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 240, 30));

        jButton3.setBackground(new java.awt.Color(153, 153, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 60, 80, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 640, 340));

        btnUpdate.setBackground(new java.awt.Color(153, 153, 255));
        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 60, 100, 30));

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 90, 30));

        btnApprove.setBackground(new java.awt.Color(153, 153, 255));
        btnApprove.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnApprove.setText("APPROVE");
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });
        jPanel1.add(btnApprove, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
                            
    // Inig click sa "USERS", automatic mo-load ang data gikan sa database
    displayUsers(); 

    }//GEN-LAST:event_jLabel6MouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        
                                              
                                        
    String idToDelete = javax.swing.JOptionPane.showInputDialog(this, "Please enter the User ID you wish to delete:");

    if (idToDelete == null) return; // User clicked Cancel

    if (idToDelete.trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: ID cannot be empty.", "Validation Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Confirmation
    int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to permanently delete User ID: " + idToDelete + "?", 
            "Confirm Deletion", javax.swing.JOptionPane.YES_NO_OPTION);

    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
        try {
            java.sql.Connection conn = java.sql.DriverManager.getConnection("jdbc:sqlite:info.db");
            String sql = "DELETE FROM tbl_user WHERE id = ?";
            java.sql.PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, idToDelete);

            int rowsDeleted = pstmt.executeUpdate();
            
            if (rowsDeleted > 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Success: User ID " + idToDelete + " has been removed.");
                displayUsers();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Notice: No user found with ID " + idToDelete + ".", "Record Not Found", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
            conn.close();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Delete Error: " + e.getMessage());
        }
    }



    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
                                           
   // KINI ANG USBA SA IMONG SEARCH CODE
try {
    Connection conn = DriverManager.getConnection("jdbc:sqlite:info.db");
    
    // I-apil ang role ug status sa SELECT statement
    String sql = "SELECT id, fullname, email, role, status FROM tbl_user WHERE fullname LIKE ? OR email LIKE ?";
    PreparedStatement pstmt = conn.prepareStatement(sql);
    pstmt.setString(1, "%" + jTextField1.getText() + "%");
    pstmt.setString(2, "%" + jTextField1.getText() + "%");
    ResultSet rs = pstmt.executeQuery();

    // Kuhaa ang model sa imong jTable1
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0); // I-clear ang table sa dili pa mo-display og bag-o

    while (rs.next()) {
        // I-add ang 5 ka data sa array para sa 5 ka columns
        model.addRow(new Object[]{
            rs.getInt("id"),
            rs.getString("fullname"),
            rs.getString("email"),
            rs.getString("role"),   // Bag-ong gi-add
            rs.getString("status")  // Bag-ong gi-add
        });
    }
    conn.close();
} catch (Exception e) {
    System.out.println("Search Error: " + e.getMessage());
}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyReleased

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:               
                                      
  // I-pasa ang email sa user ngadto sa EditProfile
EditProfile ep = new EditProfile(this.adminEmail); 
    ep.setVisible(true);
    ep.setLocationRelativeTo(null);

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
                                 
  int row = jTable1.getSelectedRow();
    if (row != -1) {
        // Kuhaa ang fullname gikan sa column 1 (Index 1)
        String name = jTable1.getValueAt(row, 1).toString();
        jTextField1.setText(name); 
    }



    }//GEN-LAST:event_jTable1MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
       
    int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to logout?", "Logout Confirmation", 
            javax.swing.JOptionPane.YES_NO_OPTION);

   
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
        new landing().setVisible(true); 
        this.dispose(); 
    
}
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked

  
    if (this.adminEmail != null && !this.adminEmail.isEmpty()) {
        // Ablihan ang profile page ug ipasa ang email
        myprofile mp = new myprofile(this.adminEmail); 
        mp.setVisible(true);
        
        // Isira ang dashboard
        this.dispose(); 
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: Session email not found!");
    }


    // Optional: If you want to close the dashboard when profile opens
    // this.dispose(); 

    }//GEN-LAST:event_jLabel1MouseClicked

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
        // TODO add your handling code here:
                                            
    int row = jTable1.getSelectedRow();
    
    // Check kung naay gi-select nga user sa table
    if (row == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select a user from the table first!");
        return;
    }

    // Kuhaon ang ID gikan sa column 0 sa napili nga row
    String id = jTable1.getValueAt(row, 0).toString();
    String name = jTable1.getValueAt(row, 1).toString();

    // Confirm sa admin kung i-approve ba gyud
    int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to approve " + name + "?", "Confirm Approval", 
            javax.swing.JOptionPane.YES_NO_OPTION);

    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
        try {
            java.sql.Connection conn = java.sql.DriverManager.getConnection("jdbc:sqlite:info.db");
            // I-update ang status ngadto sa 'Active'
            String sql = "UPDATE tbl_user SET status = 'Active' WHERE id = ?";
            java.sql.PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, id);
            
            int result = pstmt.executeUpdate();
            
            if (result > 0) {
                javax.swing.JOptionPane.showMessageDialog(this, name + " is now ACTIVE!");
                displayUsers(); // I-refresh ang table para makita ang bag-ong status
            }
            
            conn.close();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }

        
    }//GEN-LAST:event_btnApproveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                                         
    // 1. I-initialize ang imong bag-ong frame
    createUser addFrame = new createUser();
    
    // 2. I-pakita ang frame
    addFrame.setVisible(true);
    
    // 3. (Optional) I-center ang frame sa screen
    addFrame.setLocationRelativeTo(null);

        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        ReportFrame rf = new ReportFrame();
    
    // 2. I-pakita ang ReportFrame
    rf.setVisible(true);
    
    // 3. I-center kini sa screen (optional)
    rf.setLocationRelativeTo(null);
    
    // 4. Isira o i-hide ang dashboard (pilia ang usa)
    this.dispose(); // Gamita kini kung gusto nimo isira ang dashboard

    }//GEN-LAST:event_jLabel9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_dashboard().setVisible(true);
            }
        });
    }
   public void displayUsers() {
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
    model.setColumnCount(0); 
    model.addColumn("ID");       // Column index 0
    model.addColumn("Fullname"); // Column index 1
    model.addColumn("Email");    // Column index 2
    model.addColumn("Role");     // Column index 3
    model.addColumn("Status");
    model.setRowCount(0); 

    try {
        java.sql.Connection conn = java.sql.DriverManager.getConnection("jdbc:sqlite:info.db");
        java.sql.Statement stmt = conn.createStatement();
        // 1. I-apil ang 'id' sa imong SELECT query
        java.sql.ResultSet rs = stmt.executeQuery("SELECT id, fullname, email, role, status FROM tbl_user");

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("id"),       // I-load ang ID sa column 0
                rs.getString("fullname"), // Column 1
                rs.getString("email"),    // Column 2
                rs.getString("role"),
                rs.getString("status")
    
            });
        }
        conn.close();
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }

}
   private void displayAdminName() {
   
    try {
        java.sql.Connection conn = java.sql.DriverManager.getConnection("jdbc:sqlite:info.db");
        // I-apil ang profile_pic sa SELECT statement
        String sql = "SELECT fullname, profile_pic FROM tbl_user WHERE email = ?";
        java.sql.PreparedStatement pstmt = conn.prepareStatement(sql);
        pstmt.setString(1, adminEmail);
        java.sql.ResultSet rs = pstmt.executeQuery();

        if (rs.next()) {
            // I-display ang Fullname sa label
            String name = rs.getString("fullname");
            lblAdminName.setText(name); 
            
            // I-display ang Profile Picture sa jLabel3 (o jLabel8)
            String path = rs.getString("profile_pic");
            if (path != null && !path.isEmpty()) {
                javax.swing.ImageIcon icon = new javax.swing.ImageIcon(path);
                // I-resize ang image base sa gidak-on sa jLabel3
                java.awt.Image img = icon.getImage().getScaledInstance(jLabel3.getWidth(), jLabel3.getHeight(), java.awt.Image.SCALE_SMOOTH);
                jLabel3.setIcon(new javax.swing.ImageIcon(img));
                jLabel3.setText(""); // Tangtangon ang "jLabel3" nga text
            }
        }
        conn.close();
    } catch (Exception e) {
        System.out.println("Error fetching admin data: " + e.getMessage());
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblAdminName;
    // End of variables declaration//GEN-END:variables

    }
