/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

/**
 *
 * @author USER16
 */
public class myprofile extends javax.swing.JFrame {

    private String userEmail; 

    // 2. Kani ang constructor nga modawat sa email gikan sa Login
    public myprofile(String email) {
        initComponents();
        this.userEmail = email; 
        showUserProfile(); // Kini nga function maoy mokuha sa data sa DB
    }
    public void showUserProfile() {
    try {
        java.sql.Connection conn = java.sql.DriverManager.getConnection("jdbc:sqlite:info.db");
        String sql = "SELECT fullname, email, role FROM tbl_user WHERE email = ?";
        java.sql.PreparedStatement pstmt = conn.prepareStatement(sql);
        pstmt.setString(1, userEmail); // Uses the email passed from the Account button
        java.sql.ResultSet rs = pstmt.executeQuery();

        if (rs.next()) {
            // Update these names to match your actual Label variable names
            lblFullname.setText(rs.getString("Fullname"));
            lblEmail.setText(rs.getString("Email"));
            lblRole.setText(rs.getString("role"));
        }
        conn.close();
    } catch (Exception e) {
        System.out.println("Error: " + e.getMessage());
    }
    }


    // 3. Importante ni para sa NetBeans Design View
    public myprofile() {
        if (UserSession.loggedInUser == null) {
    javax.swing.JOptionPane.showMessageDialog(null, "Required Login!");
    new login().setVisible(true);
    this.dispose();
    return;
}
        initComponents();
    }
    
    // 4. Idugang kini nga method sa ubos para mo-display sa data
   
  

    /**
     * Creates new f


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Fullname = new javax.swing.JPanel();
        lblFullname = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Fullname.setBackground(new java.awt.Color(153, 153, 255));
        Fullname.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFullname.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        lblFullname.setText("Fullname:");
        Fullname.add(lblFullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        lblEmail.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        lblEmail.setText("Email:");
        Fullname.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        lblRole.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        lblRole.setText("Role:");
        Fullname.add(lblRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Fullname.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 380, -1, -1));

        jPanel1.add(Fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 60, 830, 420));

        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ADMIN PROFILE");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 270, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
    Admin_dashboard ad = new Admin_dashboard(this.userEmail); 
    ad.setVisible(true);
    
    // Isira ang myprofile page
    this.dispose(); 

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(myprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(myprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(myprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(myprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new myprofile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fullname;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFullname;
    private javax.swing.JLabel lblRole;
    // End of variables declaration//GEN-END:variables
}
