/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

/**
 *
 * @author Joyce Ann
 */
public class ReportFrame extends javax.swing.JFrame {
    private String adminEmail;
    private String keyword;

    /**
     * Creates new form ReportFrame
     */
    public ReportFrame() {
         
  
    
        initComponents();
        displayTransactions();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnApprove = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REPORTS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, -1));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 640, 320));
        jPanel2.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 250, 30));

        btnSearch.setBackground(new java.awt.Color(153, 153, 255));
        btnSearch.setText("search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel2.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 80, 30));

        btnDelete.setBackground(new java.awt.Color(153, 153, 255));
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 80, -1));

        btnApprove.setBackground(new java.awt.Color(153, 153, 255));
        btnApprove.setText("APPROVE");
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });
        jPanel2.add(btnApprove, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        btnBack.setBackground(new java.awt.Color(153, 153, 255));
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel2.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 80, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 820, 410));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, -4, 830, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
      String searchKeyword = txtSearch.getText().trim(); // Kuhaon ang gi-type sa user
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
    model.setRowCount(0); 

    try {
        java.sql.Connection conn = java.sql.DriverManager.getConnection("jdbc:sqlite:info.db");
        
        // SQL query nga nag-search sa email o teacher name
        String query = "SELECT t_id, user_email, grade_level, teacher_name, section, status FROM tbl_transactions " +
                       "WHERE user_email LIKE ? OR teacher_name LIKE ? OR t_id LIKE ?";
        
        java.sql.PreparedStatement pstmt = conn.prepareStatement(query);
        pstmt.setString(1, "%" + searchKeyword + "%");
        pstmt.setString(2, "%" + searchKeyword + "%");
        pstmt.setString(3, "%" + searchKeyword + "%");

        java.sql.ResultSet rs = pstmt.executeQuery();

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("t_id"),
                rs.getString("user_email"),
                rs.getString("grade_level"),
                rs.getString("teacher_name"),
                rs.getString("section"),
                rs.getString("status")
            });
        }
        conn.close();
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(null, "Search Error: " + e.getMessage());
    }


    }//GEN-LAST:event_btnSearchActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
    
    // 2. Siguroha nga naay napili nga row
    if (row != -1) {
        // Kuhaon nato ang ID sa transaction gikan sa Column 0
        // Kini nga ID ang gamiton para sa UPDATE o DELETE SQL queries
        String transactionID = jTable1.getValueAt(row, 0).toString();
        
        // Pwede nimo i-display sa console para ma-verify nimo kung husto ang napili
        System.out.println("Selected Transactions ID: " + transactionID); 
    }

    }//GEN-LAST:event_jTable1MouseClicked

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        // Balik sa Admin Dashboard ug ipasa ang email session
    Admin_dashboard ds = new Admin_dashboard(this.adminEmail); 
    ds.setVisible(true);
    ds.setLocationRelativeTo(null); // I-center ang dashboard
    
    // Isira ang ReportFrame
    this.dispose(); 

    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
     
       String idToDelete = javax.swing.JOptionPane.showInputDialog(this, "Please enter the Transaction ID you want to delete:");

    // 2. Check if the user clicked "Cancel" or closed the dialog
    if (idToDelete == null) {
        return; 
    }

    // 3. Validation: Ensure the ID is not empty
    if (idToDelete.trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: Transaction ID cannot be empty.", "Validation Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // 4. Confirmation: Ask the user to confirm before permanently deleting
    int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to permanently delete Transaction ID: " + idToDelete + "?", 
            "Confirm Deletion", javax.swing.JOptionPane.YES_NO_OPTION);

    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
        try {
            // Establish connection to your SQLite database
            java.sql.Connection conn = java.sql.DriverManager.getConnection("jdbc:sqlite:info.db");
            
            // SQL query using the correct table 'tbl_transactions' and key 't_id'
            String sql = "DELETE FROM tbl_transactions WHERE t_id = ?";
            java.sql.PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, idToDelete);

            int rowsDeleted = pstmt.executeUpdate();
            
            if (rowsDeleted > 0) {
                // Success message
                javax.swing.JOptionPane.showMessageDialog(this, "Success: Transaction ID " + idToDelete + " has been removed.");
                // Refresh the table display to reflect changes
                displayTransactions();
            } else {
                // If the ID typed does not exist in the database
                javax.swing.JOptionPane.showMessageDialog(this, "Notice: No transaction found with ID " + idToDelete + ".", "Record Not Found", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
            
            conn.close();
        } catch (Exception e) {
            // Handle any database errors (e.g., database file not found)
            javax.swing.JOptionPane.showMessageDialog(this, "Delete Error: " + e.getMessage());
        }
    }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
        // TODO add your handling code here:
        String idToUpdate = javax.swing.JOptionPane.showInputDialog(this, "Please enter the Transaction ID (t_id):");

    if (idToUpdate == null || idToUpdate.trim().isEmpty()) return;

    // 2. Maghimo og Selection Buttons para sa Approved o Declined
    Object[] options = {"Approve", "Decline", "Cancel"};
    int choice = javax.swing.JOptionPane.showOptionDialog(this, 
            "What action would you like to take for ID: " + idToUpdate + "?", 
            "Update Status", 
            javax.swing.JOptionPane.YES_NO_CANCEL_OPTION, 
            javax.swing.JOptionPane.QUESTION_MESSAGE, 
            null, options, options[2]);

    String newStatus = "";
    if (choice == javax.swing.JOptionPane.YES_OPTION) {
        newStatus = "Approved";
    } else if (choice == javax.swing.JOptionPane.NO_OPTION) {
        newStatus = "Declined";
    } else {
        return; // User clicked Cancel or closed the dialog
    }

    // 3. I-execute ang Update sa Database
    try {
        java.sql.Connection conn = java.sql.DriverManager.getConnection("jdbc:sqlite:info.db");
        
        // SQL query para sa tbl_transactions
        String sql = "UPDATE tbl_transactions SET status = ? WHERE t_id = ?";
        java.sql.PreparedStatement pstmt = conn.prepareStatement(sql);
        pstmt.setString(1, newStatus);
        pstmt.setString(2, idToUpdate);

        int rowsUpdated = pstmt.executeUpdate();
        
        if (rowsUpdated > 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Success: Transaction " + idToUpdate + " is now " + newStatus + ".");
            displayTransactions(); // Refresh ang table
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "ID not found.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        conn.close();
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Update Error: " + e.getMessage());
    }

    }//GEN-LAST:event_btnApproveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    private void displayTransactions() {
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
    
    // I-setup ang columns base sa imong database screenshot
    model.setColumnCount(0); 
    model.addColumn("ID");
    model.addColumn("Email");
    model.addColumn("Grade Level");
    model.addColumn("Teacher");
    model.addColumn("Section");
    model.addColumn("Status");
    
    model.setRowCount(0); 

    try {
        java.sql.Connection conn = java.sql.DriverManager.getConnection("jdbc:sqlite:info.db");
        java.sql.Statement stmt = conn.createStatement();
        
        // GI-FIX: Gidugangan og 's' ang tbl_transactions ug gi-update ang column names
        String query = "SELECT t_id, user_email, grade_level, teacher_name, section, status FROM tbl_transactions";
        java.sql.ResultSet rs = stmt.executeQuery(query);

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("t_id"),
                rs.getString("user_email"),
                rs.getString("grade_level"),
                rs.getString("teacher_name"),
                rs.getString("section"),
                rs.getString("status")
            });
        }
        conn.close();
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(null, "Database Error: " + e.getMessage());
    }
}
}