/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

/**
 *
 * @author Joyce Ann
 */
public class Student_dashboard extends javax.swing.JFrame {
   
    private String userEmail; 


    public Student_dashboard() {
        initComponents();
    }

    public Student_dashboard(String email) {
        this.userEmail = email; 
        initComponents();
        displayUserProfile();
        System.out.println("Student logged in: " + email);
    
    }
public void displayUserProfile() {
        // I-select ang fullname, email, ug role base sa imong info.db
        try (java.sql.Connection conn = config.config.connectDB(); 
             java.sql.PreparedStatement pstmt = conn.prepareStatement("SELECT fullname, email, role FROM tbl_user WHERE email = ?")) {
            
            pstmt.setString(1, userEmail); 
            java.sql.ResultSet rs = pstmt.executeQuery();
            
            if (rs.next()) {
                // Pagkuha sa data gikan sa database
                String name = rs.getString("fullname");
                String email = rs.getString("email");
                String role = rs.getString("role");
                
                // I-display sa imong mga labels base sa imong variables sa ubos
                lblFullname.setText(name); 
                lblEmail.setText(email);  // Mao ni ang variable name sa imong email label
                lblRole.setText(role); // Mao ni ang variable name sa imong role label
            }
        } catch (java.sql.SQLException e) {
            System.out.println("Error loading profile: " + e.getMessage());
        }
    

  
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblFullname = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 1, 24)); // NOI18N
        jLabel1.setText("Student Dashboard");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 13, 238, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 50));

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFullname.setBackground(new java.awt.Color(204, 204, 204));
        lblFullname.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        lblFullname.setText("FullName:");
        jPanel3.add(lblFullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 190, 30));

        lblEmail.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        lblEmail.setText("Email:");
        jPanel3.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 170, 30));

        lblRole.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        lblRole.setText("Role:");
        jPanel3.add(lblRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 140, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 400, 190));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-11, -4, 760, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student_dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFullname;
    private javax.swing.JLabel lblRole;
    // End of variables declaration//GEN-END:variables
}