/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Joyce Ann
 */
public class Student_dashboard extends javax.swing.JFrame {
    
   private String userEmail;

    /**
     * Creates new form Student_dashboard
     */
    public Student_dashboard() {
        initComponents();
    }
    Student_dashboard(String email) {
   this.userEmail = email; 
    initComponents();       
    displayUserProfile();   
    displayTransactions(); // Tawgon kini para load dayon ang data sa table

    // --- KINI NGA MGA LINYA ANG NAG-HIDE SA COMPONENTS ---
    // Atong i-set og TRUE ang tanan para makita sila
    
    jLabel8.setVisible(true);      // Label Teacher
    jTextField1.setVisible(true);  // Field Teacher
    jLabel9.setVisible(true);      // Label Section
    jTextField2.setVisible(true);  // Field Section
    jComboBox1.setVisible(true);   // Grade Level
    jLabel10.setVisible(true);     // Label Email
    jTextField3.setVisible(true);  // Field Email
    btnSubmit.setVisible(true);    // Submit Button
    jScrollPane1.setVisible(true); // Table Area

    // I-set ang email sa textfield
    jTextField3.setText(userEmail);
    jTextField3.setEditable(false); // Optional: aron dili ma-edit sa student ang email

 //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblEditProfile = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setEditable(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 200, 30));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 200, 30));

        jComboBox1.setBackground(new java.awt.Color(153, 153, 255));
        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "GRADE & LEVEL", "GRADE 7", "GRADE 8", "GRADE 9", "GRADE 10", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, -1, 30));

        jLabel8.setText("TEACHER NAME:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel9.setText("SECTION:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 620, 160));

        jLabel10.setText("Email:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 176, -1, 20));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 200, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("REQUEST GRADES");
        jLabel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 160, -1));

        jLabel2.setText("SUBJECT:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, -1, -1));
        jPanel2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 190, 30));

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, -1, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 660, 420));

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Student Dashboard");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("HOME");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 140, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("MY PROFILE");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 140, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("LOGOUT");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 140, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 150, 20));

        lblEditProfile.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEditProfile.setText("EDIT PROFILE");
        lblEditProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEditProfileMouseClicked(evt);
            }
        });
        jPanel1.add(lblEditProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 120, 90));

        btnSubmit.setBackground(new java.awt.Color(153, 153, 255));
        btnSubmit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSubmit.setText("SUBMIT");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 270, -1, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
          
    int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to logout?", "Logout Confirmation", 
            javax.swing.JOptionPane.YES_NO_OPTION);

   
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
        new landing().setVisible(true); 
        this.dispose(); 
        }
      
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
                                            
    Studentprofile sp = new Studentprofile(userEmail); 
    sp.setVisible(true);
    this.dispose(); 

    }//GEN-LAST:event_jLabel4MouseClicked

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String selectedGrade = jComboBox1.getSelectedItem().toString();
    try {
        // Connect sa imong database
        java.sql.Connection conn = java.sql.DriverManager.getConnection("jdbc:sqlite:info.db");
        
        // Mag-select ta sa teacher gikan sa imong Masterlist (tbl_subjects)
        String sql = "SELECT teacher_name FROM tbl_subjects WHERE grade_level = ? LIMIT 1";
        java.sql.PreparedStatement pstmt = conn.prepareStatement(sql);
        pstmt.setString(1, selectedGrade);
        java.sql.ResultSet rs = pstmt.executeQuery();
        
        if(rs.next()){
            // I-set ang Teacher Name sa jTextField1 (Teacher field)
            jTextField1.setText(rs.getString("teacher_name"));
        } else {
            jTextField1.setText("No Teacher Assigned");
        }
        conn.close();
    } catch (Exception e) {
        System.out.println("Error: " + e.getMessage());
    }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
  String email = jTextField3.getText();
    String grade = jComboBox1.getSelectedItem().toString();
    String teacher = jTextField1.getText();
    String section = jTextField2.getText();
    String subject = jTextField4.getText(); // Gikuha ang data gikan sa Subject field
    String status = "Pending"; 

    // Validation: Siguraduhon nga naay sulod ang Section ug Subject
    if(section.trim().isEmpty() || subject.trim().isEmpty()){
        javax.swing.JOptionPane.showMessageDialog(this, "Palihog pun-i ang Section ug Subject!");
        return;
    }

    try {
        java.sql.Connection conn = java.sql.DriverManager.getConnection("jdbc:sqlite:info.db");
        
        // Gi-apil ang 'subject' sa SQL query
        String sql = "INSERT INTO tbl_transactions (user_email, grade_level, teacher_name, section, subject, status) VALUES (?, ?, ?, ?, ?, ?)";
        java.sql.PreparedStatement pstmt = conn.prepareStatement(sql);
        
        pstmt.setString(1, email);
        pstmt.setString(2, grade);
        pstmt.setString(3, teacher);
        pstmt.setString(4, section);
        pstmt.setString(5, subject); // I-save ang subject
        pstmt.setString(6, status);

        pstmt.executeUpdate();
        javax.swing.JOptionPane.showMessageDialog(this, "Request Submitted Successfully!");
        
        displayTransactions(); // Refresh ang table
        
        // Limpyohan ang mga fields human ma-submit
        jTextField2.setText(""); 
        jTextField4.setText(""); 
        
        conn.close();
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }

    }//GEN-LAST:event_btnSubmitActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
                                         
    int row = jTable1.getSelectedRow();
    
    // 2. Siguroha nga naay napili nga row (dili -1)
    if (row != -1) {
        // Kuhaa ang data gikan sa columns base sa index niini (0, 1, 2...)
        // Pananglitan: Column 1 = Grade Level, Column 2 = Teacher Name
        
        String gradeLevel = jTable1.getValueAt(row, 1).toString();
        String teacherName = jTable1.getValueAt(row, 2).toString();
        String section = jTable1.getValueAt(row, 3).toString();
        
        // 3. I-display ang data balik sa imong mga fields
        jComboBox1.setSelectedItem(gradeLevel); // Para sa Grade Level dropdown
        jTextField1.setText(teacherName);      // Para sa Teacher Name field
        jTextField2.setText(section);          // Para sa Section field
        
        // Optional: I-pakita ang mga labels/fields kon pananglitan naka-tago sila
        jLabel8.setVisible(true);
        jTextField1.setVisible(true);
        jLabel9.setVisible(true);
        jTextField2.setVisible(true);
        jComboBox1.setVisible(true);
    }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void lblEditProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditProfileMouseClicked
        // TODO add your handling code here:
        EditProfile ep = new EditProfile(this.userEmail); 
    
    // 3. I-pakita ang frame
    ep.setVisible(true);
    
    // 4. I-center ang frame sa screen
    ep.setLocationRelativeTo(null);
    
    // 5. (Optional) I-close o i-hide ang dashboard kung gusto nimo
    // this.dispose(); 

    }//GEN-LAST:event_lblEditProfileMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String email = jTextField3.getText();
    String grade = jComboBox1.getSelectedItem().toString();
    String teacher = jTextField1.getText();
    String section = jTextField2.getText();
    String subject = jTextField4.getText(); 
    String status = "Pending"; 

    // 2. Validation: Siguraduhon nga dili empty ang importante nga fields
    if(section.trim().isEmpty() || subject.trim().isEmpty() || grade.equals("GRADE & LEVEL")){
        javax.swing.JOptionPane.showMessageDialog(this, "Palihog pun-i ang tanang fields (Section, Subject, Grade)!");
        return;
    }

    try {
        // 3. Koneksyon sa Database
        java.sql.Connection conn = java.sql.DriverManager.getConnection("jdbc:sqlite:info.db");
        
        // 4. SQL Query - Siguraduhon nga match ang gidaghanon sa columns ug ?
        String sql = "INSERT INTO tbl_transactions (user_email, grade_level, teacher_name, section, subject, status) VALUES (?, ?, ?, ?, ?, ?)";
        java.sql.PreparedStatement pstmt = conn.prepareStatement(sql);
        
        pstmt.setString(1, email);
        pstmt.setString(2, grade);
        pstmt.setString(3, teacher);
        pstmt.setString(4, section);
        pstmt.setString(5, subject);
        pstmt.setString(6, status);

        // 5. Pag-execute sa SQL
        pstmt.executeUpdate();
        
        // 6. Feedback sa user
        javax.swing.JOptionPane.showMessageDialog(this, "Request Submitted Successfully!");
        
        // 7. REFRESH SA TABLE - Tawgon ang imong existing function para makita dayon ang data
        displayTransactions(); 
        
        // 8. Limpyohan ang mga fields human ma-submit
        jTextField2.setText(""); 
        jTextField4.setText(""); 
        jComboBox1.setSelectedIndex(0);
        jTextField1.setText("");
        
        conn.close();
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                if (UserSession.loggedInUser == null) {
    javax.swing.JOptionPane.showMessageDialog(null, "Required Login!");
    new login().setVisible(true);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lblEditProfile;
    // End of variables declaration//GEN-END:variables

    private void displayUserProfile() {
        
     try {
        java.sql.Connection conn = config.config.connectDB();
        // Gi-apil ang profile_pic sa SELECT statement
        String sql = "SELECT fullname, profile_pic FROM tbl_user WHERE email = ?";
        java.sql.PreparedStatement pstmt = conn.prepareStatement(sql);
        pstmt.setString(1, userEmail); 
        java.sql.ResultSet rs = pstmt.executeQuery();

        if (rs.next()) {
            // 1. I-set ang Title sa babaw (jLabel1)
            jLabel1.setText("STUDENT DASHBOARD"); 
            
            // 2. I-set ang Fullname sa student (jLabel7)
            jLabel7.setText(rs.getString("fullname")); 
            
            // 3. I-set ang Picture sa student (jLabel11)
            String path = rs.getString("profile_pic");
            if (path != null && !path.isEmpty()) {
                javax.swing.ImageIcon icon = new javax.swing.ImageIcon(path);
                
                // I-resize ang image base sa gidak-on sa jLabel11 sa imong design
                java.awt.Image img = icon.getImage().getScaledInstance(
                    jLabel11.getWidth(), 
                    jLabel11.getHeight(), 
                    java.awt.Image.SCALE_SMOOTH
                );
                
                jLabel11.setIcon(new javax.swing.ImageIcon(img));
                jLabel11.setText(""); // Tangtangon ang text nga "jLabel11"
            }
        }
        rs.close();
        pstmt.close();
        conn.close();
    } catch (Exception e) {
        System.out.println("Error loading profile: " + e.getMessage());
    }

}

private void displayTransactions() {
    String[] columnNames = {"ID", "Email", "Grade Level", "Teacher", "Section", "Subject", "Status"};
    javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(columnNames, 0);
    jTable1.setModel(model); 

    try {
        java.sql.Connection conn = java.sql.DriverManager.getConnection("jdbc:sqlite:info.db");
        // Gi-apil ang 'subject' sa SELECT query
        String sql = "SELECT t_id, user_email, grade_level, teacher_name, section, subject, status FROM tbl_transactions WHERE user_email = ?";
        java.sql.PreparedStatement pstmt = conn.prepareStatement(sql);
        pstmt.setString(1, userEmail); 
        java.sql.ResultSet rs = pstmt.executeQuery();

        while(rs.next()){
            model.addRow(new Object[]{
                rs.getInt("t_id"),
                rs.getString("user_email"),
                rs.getString("grade_level"),
                rs.getString("teacher_name"),
                rs.getString("section"),
                rs.getString("subject"), // I-display ang subject sa table
                rs.getString("status")
            });
        }
        conn.close();
    } catch (Exception e) {
        System.out.println("Error: " + e.getMessage());
    }
}
}