/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

/**
 *
 * @author Joyce Ann
 */
public class Studentprofile extends javax.swing.JFrame {
   
    private String userEmail; 


    public Studentprofile() {
        if (UserSession.loggedInUser == null) {
    javax.swing.JOptionPane.showMessageDialog(null, "Required Login!");
    new login().setVisible(true);
    this.dispose();
    return;
}
        initComponents();
    }

    public Studentprofile(String email) {
        this.userEmail = email; 
        initComponents();
        displayUserProfile();
        System.out.println("Student logged in: " + email);
    
    }
public void displayUserProfile() {
try {
        java.sql.Connection conn = config.config.connectDB(); 
        // Gidugangan og profile_pic ang SELECT statement
        String sql = "SELECT fullname, email, role, profile_pic FROM tbl_user WHERE email = ?";
        java.sql.PreparedStatement pstmt = conn.prepareStatement(sql);
        pstmt.setString(1, userEmail); 
        java.sql.ResultSet rs = pstmt.executeQuery();

        if (rs.next()) {
            lblFullname.setText("Full Name: " + rs.getString("fullname"));
            lblEmail.setText("Email: " + rs.getString("email"));
            lblRole.setText("Role: " + rs.getString("role"));
            
            // --- LOGIC PARA SA PICTURE ---
            String path = rs.getString("profile_pic");
            if (path != null && !path.isEmpty()) {
                javax.swing.ImageIcon icon = new javax.swing.ImageIcon(path);
                // I-resize ang image aron mo-igo sa lbl_img nga label
                java.awt.Image img = icon.getImage().getScaledInstance(lbl_img.getWidth(), lbl_img.getHeight(), java.awt.Image.SCALE_SMOOTH);
                lbl_img.setIcon(new javax.swing.ImageIcon(img));
                lbl_img.setText(""); // Tangtangon ang default text
            } else {
                lbl_img.setText("No Image");
                lbl_img.setIcon(null);
            }
        }
        conn.close();
    } catch (Exception e) {
        System.out.println("Error: " + e.getMessage());
    }

  
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblFullname = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lbl_img = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFullname.setBackground(new java.awt.Color(204, 204, 204));
        lblFullname.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        lblFullname.setText("FullName:");
        jPanel3.add(lblFullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 190, 30));

        lblEmail.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        lblEmail.setText("Email:");
        jPanel3.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 170, 30));

        lblRole.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        lblRole.setText("Role:");
        jPanel3.add(lblRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 140, 30));

        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, -1, -1));

        lbl_img.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(lbl_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 140, 120));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 820, 430));

        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("STUDENT PROFILE");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 280, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Student_dashboard(userEmail).setVisible(true); 
    
    // I-close ang kasamtangan nga profile frame
    this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Studentprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Studentprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Studentprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Studentprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Studentprofile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFullname;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lbl_img;
    // End of variables declaration//GEN-END:variables
}